modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="lord_of_the_rings_mod"
version="1.0.0"
displayName="Lord Of The Rings Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jonathandillon"

[[dependencies.lord_of_the_rings_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



